
import { createStitches } from '@stitches/react';

export const {
  styled,
  css,
  globalCss,
  keyframes,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      primary: '#2563eb',
      primaryLight: '#3b82f6',
      primaryDark: '#1d4ed8',
      secondary: '#0f172a',
      accent: '#f59e0b',
      background: '#0a0a0a',
      surface: '#171717',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      error: '#ef4444',
      success: '#22c55e',
      border: 'rgba(255, 255, 255, 0.08)',
      glass: 'rgba(255, 255, 255, 0.03)',
    },
    space: {
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      8: '32px',
      10: '40px',
      12: '48px',
      16: '64px',
    },
    fontSizes: {
      xs: '12px',
      sm: '14px',
      base: '16px',
      lg: '18px',
      xl: '20px',
      '2xl': '24px',
      '3xl': '30px',
      '4xl': '36px',
    },
    fonts: {
      sans: 'Inter, system-ui, -apple-system, sans-serif',
      display: 'Righteous, cursive',
    },
    fontWeights: {
      light: 300,
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      black: 900,
    },
    radii: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
      '2xl': '24px',
      full: '9999px',
    },
    shadows: {
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      premium: '0 20px 25px -5px rgba(0, 0, 0, 0.2), 0 10px 10px -5px rgba(0, 0, 0, 0.1)',
      glow: '0 0 15px rgba(37, 99, 235, 0.3)',
    },
    zIndices: {
      hide: -1,
      base: 0,
      docked: 10,
      dropdown: 1000,
      sticky: 1100,
      banner: 1200,
      overlay: 1300,
      modal: 1400,
      popover: 1500,
      skipLink: 1600,
      toast: 1700,
      tooltip: 1800,
    },
  },
  utils: {
    marginX: (value: any) => ({ marginLeft: value, marginRight: value }),
    marginY: (value: any) => ({ marginTop: value, marginBottom: value }),
    paddingX: (value: any) => ({ paddingLeft: value, paddingRight: value }),
    paddingY: (value: any) => ({ paddingTop: value, paddingBottom: value }),
    size: (value: any) => ({ width: value, height: value }),
  },
  media: {
    sm: '(min-width: 640px)',
    md: '(min-width: 768px)',
    lg: '(min-width: 1024px)',
    xl: '(min-width: 1280px)',
  },
});

export const globalStyles = globalCss({
  '*': { boxSizing: 'border-box' },
  body: {
    margin: 0,
    backgroundColor: '$background',
    color: '$text',
    fontFamily: '$sans',
    WebkitFontSmoothing: 'antialiased',
    MozOsxFontSmoothing: 'grayscale',
  },
  'input, textarea, select': {
    color: '#0f172a',
    backgroundColor: '#ffffff',
    caretColor: '#2563eb',
  },
  'input::placeholder, textarea::placeholder': {
    color: '#64748b',
    opacity: 1,
  },
  '.dark input, .dark textarea, .dark select': {
    color: '#f8fafc',
    backgroundColor: '#1e293b',
  },
  '.dark input::placeholder, .dark textarea::placeholder': {
    color: '#94a3b8',
  },
  '.btn': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    borderRadius: '0.75rem',
    padding: '0.75rem 1rem',
    fontWeight: 800,
    fontSize: '0.875rem',
    transition: 'all 0.2s ease',
    border: '1px solid transparent',
    cursor: 'pointer',
  },
  '.btn:disabled': {
    opacity: 0.55,
    cursor: 'not-allowed',
  },
  '.btn-primary': {
    background: 'linear-gradient(135deg, #2563eb, #1d4ed8)',
    color: '#ffffff',
    borderColor: '#1d4ed8',
    boxShadow: '0 12px 30px rgba(37, 99, 235, 0.22)',
  },
  '.btn-primary:hover:not(:disabled)': {
    background: 'linear-gradient(135deg, #1d4ed8, #1e40af)',
    transform: 'translateY(-1px)',
  },
  '.btn-secondary': {
    backgroundColor: '#ffffff',
    color: '#0f172a',
    borderColor: '#cbd5e1',
    boxShadow: '0 6px 18px rgba(15, 23, 42, 0.08)',
  },
  '.btn-secondary:hover:not(:disabled)': {
    backgroundColor: '#f8fafc',
    borderColor: '#94a3b8',
  },
  '.btn-danger': {
    backgroundColor: '#dc2626',
    color: '#ffffff',
    borderColor: '#b91c1c',
    boxShadow: '0 12px 24px rgba(220, 38, 38, 0.18)',
  },
  '.btn-danger:hover:not(:disabled)': {
    backgroundColor: '#b91c1c',
  },
  '.dark .btn-secondary': {
    backgroundColor: '#1e293b',
    color: '#f8fafc',
    borderColor: '#475569',
    boxShadow: 'none',
  },
  '.dark .btn-secondary:hover:not(:disabled)': {
    backgroundColor: '#334155',
    borderColor: '#64748b',
  },
  '.dark .btn-primary': {
    background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
    borderColor: '#2563eb',
  },
  '.dark .btn-danger': {
    backgroundColor: '#dc2626',
    borderColor: '#ef4444',
  },
});
